version: '3.8'

services:
  web:
    build:
      context: ./deepra_test
      dockerfile: Dockerfile
    command: gunicorn deepra_test.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
      
  nginx:
    build: ./nginx
    ports:
      - 8001:80
    depends_on:
      - web
